version: '3.8'

services:
  backend:
    build: ./backend
    container_name: api-r-biologicas
    ports:
      - "8000:8000" # Libera a porta 8000 da VM para acessar o container
    restart: unless-stopped # Faz o container voltar sozinho se a VM reiniciar