# Habilita os módulos de proxy do Apache
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so

# Configura o Proxy para repassar requisições da URL /api/ para o R (na porta 8000)
ProxyPass /analise-redes-biologicas/api/ http://backend:8000/
ProxyPassReverse /analise-redes-biologicas/api/ http://backend:8000/